import { Inter } from "next/font/google";
import "./globals.css";
import { LocationIcon } from "./components/Icons";
import Hero from "./components/Hero";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-screen ${inter.className}`}>
        <div className="w-full flex items-center justify-between p-2 px-8 bg-[#c96725] text-white text-sm">
          <h3 className=" ">Delivery Area</h3>
          <div className="flex items-center justify-center gap-2">
            <LocationIcon className={"!w-4"} /> Lagos
          </div>
        </div>
        <div className="w-full">
          <Hero />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
